cd version: 2
updates:
  - package-ecosystem: npm
    versioning-strategy: "increase"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/studio"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
